<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Magenta\Bundle\SWarrantyModelBundle\Entity\Media;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Magenta\Bundle\SWarrantyModelBundle\Entity\Media\Base\AppGallery;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
/**
 * @ORM\Entity
 * @ORM\Table(name="media__gallery")
 *
 *
 */
class Gallery extends AppGallery
{
    function __construct()
    {
        parent::__construct();
        $this->children = new ArrayCollection();
        $this->context = 'default';
        $this->enabled = true;
        $this->position = 0;
    }

    public function hasMedium(Media $medium)
    {
        $criteria = Criteria::create();
        $expr = Criteria::expr();

        $criteria->where(
            $expr->andX(
                $expr->eq('media', $medium),
                $expr->eq('enabled', true)
            )
        );
        return ($this->getGalleryHasMedias()->matching($criteria)->count() > 0);
    }

    /**
     * @return ArrayCollection
     */
    public function getGalleryHasMedias()
    {
        $criteria = Criteria::create();
        $expr = Criteria::expr();

        $criteria->where(
            $expr->eq('enabled', true)
        );
        return $this->galleryHasMedias->matching($criteria);
    }

}
