sonata_doctrine_orm_admin:
    templates:
        form: ['@MagentaSWarrantyAdmin/Form/fields.html.twig']

sonata_admin:
    title: 'Smart Warranty'
    options:
        title_mode: 'single_text'

    security:
        handler: magenta_swarranty.admin.security.handler.role
#        handler: Magenta\Bundle\SWarrantyAdminBundle\Security\Handler\RoleSecurityHandler
#        handler: sonata.admin.security.handler.role
#        handler: app.admin.security.handler.role
#        handler: sonata.admin.security.handler.acl
        role_admin: ROLE_POWER_USER
        role_super_admin: ROLE_ADMIN

    templates:
        layout: '@MagentaSWarrantyAdmin/standard_layout.html.twig'
        user_block: '@MagentaSWarrantyAdmin/Core/user_block.html.twig'

    assets:
        extra_stylesheets:
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-red-light.min.css
            - bundles/magentaswarrantyadmin/admin.css
        remove_stylesheets:
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
    dashboard:
        blocks: ~
#            - { type: sonata.admin.block.admin_list, position: left }

        groups:

            product:
                label: dashboard.product
                icon: '<i class="fa fa-product-hunt"></i>'
                items:
                    - Magenta\Bundle\SWarrantyAdminBundle\Admin\Product\BrandAdmin
                    - Magenta\Bundle\SWarrantyAdminBundle\Admin\Product\ServiceZoneAdmin

            system:
                label: dashboard.system
                icon: '<i class="fa fa-users"></i>'
                items:
                    - Magenta\Bundle\SWarrantyAdminBundle\Admin\User\UserAdmin
                    - Magenta\Bundle\SWarrantyAdminBundle\Admin\AccessControl\ACLAdmin
                    - Magenta\Bundle\SWarrantyAdminBundle\Admin\Organisation\OrganisationAdmin
#                    - Sonata\MediaBundle\Admin\MediaAdmin
#                    - sonata.media.admin.media
#                    - sonata.user.admin.group
#                    - sonata.classification.admin.context
#                    - sonata.classification.admin.category
#                    - sonata.classification.admin.collection
#                    - sonata.classification.admin.tag
#                    - sonata.notification.admin.message

    title_logo: https://www.magenta-consulting.com/images/logo.png
    search: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

twig:
    form_themes:
            # other files
#        - 'SonataMediaBundle:Form:media_widgets.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
#        - 'BeanLocationBundle:Form:google_maps.html.twig'
#        - 'SonataFormatterBundle:Form:formatter.html.twig'
        - '@MagentaSWarrantyAdmin/Form/fields.html.twig'