doctrine:
    dbal:
        types:
            magenta_json: Magenta\Bundle\SWarrantyModelBundle\Doctrine\Types\JsonType
security:
    encoders:
        Magenta\Bundle\SWarrantyModelBundle\Entity\User\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_ALLOWED_TO_SWITCH: ~
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # set access_strategy to unanimous, else you may have unexpected behaviors
    access_decision_manager:
        strategy: unanimous

    providers:
        magenta_user:
            id: magenta_user.user_provider.username