magenta_user:
    resource: "@MagentaSWarrantyAdminBundle/Resources/config/routing/all.xml"
    prefix: '%SYSTEM_PREFIX%'

magenta_custom_routes:
    resource: "@MagentaSWarrantyAdminBundle/Resources/config/routing/front_routes.yaml"
    prefix: /front

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#fos_user_profile_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

#fos_user_registration:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register