bean_dev_tool:
    library_source: D:\workspace\libraries\swarranty\
    library_workspace: D:\workspace\magenta\swarranty\dev\libraries\
    components: ~
    bundles:
        - MagentaSWarrantyModelBundle
        - MagentaSWarrantyAdminBundle
        - MagentaSWarrantyApiBundle
        - MagentaSWarrantyJWTBundle
        - MagentaSWarrantyMediaApiBundle
        - MagentaAppPdfBundle
