bean_dev_tool:
    library_source: E:\wamp31\www\libraries\
    library_workspace: E:\wamp31\www\swarranty\sw-dev\libraries\
    components: ~
    bundles:
        - MagentaSWarrantyModelBundle
        - MagentaSWarrantyAdminBundle
        - MagentaSWarrantyApiBundle
        - MagentaSWarrantyJWTBundle
        - MagentaSWarrantyMediaApiBundle
        - MagentaAppPdfBundle
