#organisation_contactable_members:
#    path:     /organisations/{id}/contactable-members
#    controller: Magenta\Bundle\CBookApiBundle\Controller\Organisation\OrgMemberController::contactableMembersAction
#    defaults:
#        _api_resource_class: 'Magenta\Bundle\CBookModelBundle\Entity\Organisation\Organisation'
#        _api_item_operation_name: 'get_contactable_members'
##        _api_collection_operation_name: 'books'
#
customer_update:
    path:     /customers/update
    controller: Magenta\Bundle\SWarrantyApiBundle\Controller\Customer\CustomerController::updateAction
    methods: ['POST']
    defaults:
        _api_resource_class: 'Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\Customer'
        _api_item_operation_name: 'get_customers_update'
        _api_collection_operation_name: 'post_customers_update'

