#organisation_contactable_members:
#    path:     /organisations/{id}/contactable-members
#    controller: Magenta\Bundle\CBookApiBundle\Controller\Organisation\OrgMemberController::contactableMembersAction
#    defaults:
#        _api_resource_class: 'Magenta\Bundle\CBookModelBundle\Entity\Organisation\Organisation'
#        _api_item_operation_name: 'get_contactable_members'
##        _api_collection_operation_name: 'books'
#
brand_categories:
    path:     /brands/{id}/brand-categories
    controller: Magenta\Bundle\SWarrantyApiBundle\Controller\Product\BrandController::categoriesAction
    defaults:
        _api_resource_class: 'Magenta\Bundle\SWarrantyModelBundle\Entity\Product\Brand'
        _api_item_operation_name: 'get_brand_categories'
        _api_collection_operation_name: 'categories'

category_products:
    path:     /brand-categories/{id}/products
    controller: Magenta\Bundle\SWarrantyApiBundle\Controller\Product\BrandCategoryController::productsAction
    defaults:
        _api_resource_class: 'Magenta\Bundle\SWarrantyModelBundle\Entity\Product\BrandCategory'
        _api_item_operation_name: 'get_category_products'
        _api_collection_operation_name: 'products'

#organisation_book_chapters:
#    path:     /books/{id}/chapters
#    controller: Magenta\Bundle\CBookApiBundle\Controller\Organisation\OrgChapterController::bookChaptersAction
#    defaults:
#        _api_resource_class: 'Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrgBook'
#        _api_item_operation_name: 'get_chapters'
##        _api_collection_operation_name: 'books'
#
#organisation_book_root_chapters:
#    path:     /books/{id}/root-chapters
#    controller: Magenta\Bundle\CBookApiBundle\Controller\Organisation\OrgChapterController::bookRootChaptersAction
#    defaults:
#        _api_resource_class: 'Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrgBook'
#        _api_item_operation_name: 'get_root_chapters'
#
#organisation_chapter_sub_chapters:
#    path:     /chapters/{id}/sub-chapters
#    controller: Magenta\Bundle\CBookApiBundle\Controller\Organisation\OrgChapterController::subChaptersAction
#    defaults:
#        _api_resource_class: 'Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrgChapter'
#        _api_item_operation_name: 'get_sub_chapters'
