services:
    magenta_config.command.init_db:
        class: Magenta\Bundle\SWarrantyModelBundle\Command\Module\InitiateModuleCommand
        public: false
        arguments: ['@doctrine','@doctrine.orm.default_entity_manager']
        tags:
            - {name: "console.command", command: "magenta:module:init"}

    magenta_config.notif:system:
        class: Magenta\Bundle\SWarrantyModelBundle\Command\Notification\NotifySystemCommand
        public: false
        arguments: ['@doctrine','@doctrine.orm.default_entity_manager']
        tags:
            - {name: "console.command", command: "magenta:notif:system"}

    magenta_config.command.generate_product_search_text:
        class: Magenta\Bundle\SWarrantyModelBundle\Command\Product\GenerateProductSearchTextCommand
        public: false
        arguments: ['@doctrine','@doctrine.orm.default_entity_manager']
        tags:
        - {name: "console.command", command: "magenta:product:generate-search-text"}

    magenta_config.command.import_product:
        class: Magenta\Bundle\SWarrantyModelBundle\Command\Product\ImportProductCommand
        public: false
        arguments: ['@service_container','@doctrine','@doctrine.orm.default_entity_manager']
        tags:
        - {name: "console.command", command: "magenta:product:import"}

    magenta_config.command.update_entities:
        class: Magenta\Bundle\SWarrantyModelBundle\Command\Migration\UpdateEntitiesCommand
        public: false
        arguments: ['@doctrine','@doctrine.orm.default_entity_manager']
        tags:
            - {name: "console.command", command: "magenta:migration:update-entities"}


    magenta_config.command.switch_name_number:
        class: Magenta\Bundle\SWarrantyModelBundle\Command\Migration\SwitchProductNameNumberCommand
        public: false
        arguments: ['@doctrine','@doctrine.orm.default_entity_manager']
        tags:
        - {name: "console.command", command: "magenta:migration:switch-name-number"}
