services:
    magenta_doctrine_entity_listener_customer:
        class: Magenta\Bundle\SWarrantyModelBundle\Doctrine\Customer\CustomerListener
        arguments:
            - '@service_container'
        tags:
            - { name: doctrine.orm.entity_listener }
