#Magenta\Bundle\CBookModelBundle\Entity\User\User:
#    attributes:
#        firstName:
#            groups: ['read_user','write_user']

Magenta\Bundle\SWarrantyModelBundle\Entity\System\Thing:
    attributes:
        name:
            groups: ['read_thing','write_thing']

Magenta\Bundle\SWarrantyModelBundle\Entity\Organisation\Organisation:
    attributes:
        name:
            groups: ['read_organisation','write_organisation']
        psnLocationUrl:
            groups: ['read_organisation','write_organisation']
        psnLocationInstruction:
            groups: ['read_organisation','write_organisation']
        tos:
            groups: ['read_organisation','write_organisation']
        dataPolicy:
            groups: ['read_organisation','write_organisation']
        logo:
            groups: ['read_organisation','write_organisation']
        fieldRequirements:
            groups: ['read_organisation','write_organisation']

Magenta\Bundle\SWarrantyModelBundle\Entity\Organisation\OrganisationMember:
    attributes:
#        id:
#            groups: ['read_member','write_member']
        person:
            groups: ['read_member','write_member']
        organization:
            groups: ['read_member','write_member']
        assignedOpenCases:
            groups: ['read_member','write_member']

Magenta\Bundle\SWarrantyModelBundle\Entity\Person\Person:
    attributes:
        email:
            groups: ['read_person','write_person', 'read_person_scalar']
        name:
            groups: ['read_person','write_person', 'read_person_scalar']
        birthday:
            groups: ['read_person','write_person', 'read_person_scalar']
        user:
            groups: ['read_person','write_person']
        familyName:
            groups: ['read_person','write_person', 'read_person_scalar']
        givenName:
            groups: ['read_person','write_person', 'read_person_scalar']

Magenta\Bundle\SWarrantyModelBundle\Entity\Product\Product:
    attributes:
        modelNumber:
            groups: ['read_product','write_product']
        name:
            groups: ['read_product','write_product']
        brand:
            groups: ['read_product','write_product']
        category:
            groups: ['read_product','write_product']

Magenta\Bundle\SWarrantyModelBundle\Entity\Product\ServiceZone:
    attributes:
        name:
            groups: ['read_service_zone','write_service_zone']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\Warranty:
    attributes:
        id:
            groups: ['read_warranty', 'read_registration_warranty']
        number:
            groups: ['read_warranty','write_warranty','read_registration_warranty']
        customer:
            groups: ['read_warranty','write_warranty']
        registration:
            groups: ['read_warranty','write_warranty']
        product:
            groups: ['read_warranty','write_warranty','read_registration_warranty']
        productSerialNumber:
            groups: ['read_warranty','write_warranty','read_registration_warranty']
        purchaseDate:
            groups: ['read_warranty','write_warranty','read_registration_warranty']
        expiryDate:
            groups: ['read_warranty','write_warranty','read_registration_warranty']
        receiptImages:
            groups: ['read_warranty','write_warranty','read_registration_warranty']
        dealerName:
            groups: ['read_warranty','write_warranty','read_registration_warranty']
        dealer:
          groups: ['read_warranty','write_warranty','read_registration_warranty']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\WarrantyCase:
    attributes:
        id:
            groups: ['read_case']
        completed:
            groups: ['read_case','write_case']
        status:
            groups: ['read_case','write_case']
        number:
            groups: ['read_case','write_case']
        children:
            groups: ['read_case','write_case']
        appointmentAt:
            groups: ['read_case','write_case']
        appointments:
            groups: ['read_case','write_case']
        warranty:
            groups: ['read_case','write_case']
        serviceNotes:
            groups: ['read_case','write_case']
        serviceSheets:
            groups: ['read_case','write_case']

        createdAt:
            groups: ['read_case','write_case']
        serviceZone:
            groups: ['read_case','write_case']
        description:
            groups: ['read_case','write_case']
        specialRemarks:
            groups: ['read_case','write_case']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\CaseAppointment:
    attributes:
        id:
            groups: ['read_appointment','read_case_appointment','read_appointment_scalar', 'read_case_note']
        status:
            groups: ['read_appointment','write_appointment','read_appointment_scalar','read_case_note']
        serviceNote:
            groups: ['read_appointment','write_appointment','read_case_appointment']
        serviceSheet:
            groups: ['read_appointment','write_appointment','read_case_appointment']
        appointmentAt:
            groups: ['read_appointment','write_appointment','read_appointment_scalar','read_appointment_scalar','read_case_note']
        visitedAt:
            groups: ['read_appointment','write_appointment','read_appointment_scalar','read_case_appointment','read_case_note']
        assignee:
            groups: ['read_appointment','write_appointment']
        assigneeName:
            groups: ['read_appointment','write_appointment','read_appointment_scalar']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\Customer:
    attributes:
        organisation:
            groups: ['read_customer','write_customer']
        name:
            groups: ['read_customer','write_customer']
        email:
            groups: ['read_customer','write_customer']
        dialingCode:
            groups: ['read_customer','write_customer']
        telephone:
            groups: ['read_customer','write_customer']
        homeAddress:
            groups: ['read_customer','write_customer']
        homePostalCode:
            groups: ['read_customer','write_customer']
        addressUnitNumber:
            groups: ['read_customer','write_customer']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\NewsletterSubscription:
    attributes:
        customer:
            groups: ['read_nls','write_nls']
        email:
            groups: ['read_nls','write_nls']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\Registration:
    attributes:
        customer:
            groups: ['read_registration', 'write_registration']
        warranties:
            groups: ['read_registration', 'write_registration']
        submitted:
            groups: ['read_registration','write_registration']
        verified:
            groups: ['read_registration']
        name:
            groups: ['read_registration','write_registration']
        email:
            groups: ['read_registration','write_registration']
        dialingCode:
            groups: ['read_registration','write_registration']
        telephone:
            groups: ['read_registration','write_registration']
        homeAddress:
            groups: ['read_registration','write_registration']
        homePostalCode:
            groups: ['read_registration','write_registration']
        addressUnitNumber:
            groups: ['read_registration','write_registration']

        ageGroup:
            groups: ['read_registration','write_registration']
        hearFromOnlineSearch:
            groups: ['read_registration','write_registration']
        hearFromOnlineAd:
            groups: ['read_registration','write_registration']
        hearFromFriendFamily:
            groups: ['read_registration','write_registration']
        reasonInteriorDesigner:
            groups: ['read_registration','write_registration']
        hearWalkShop:
            groups: ['read_registration','write_registration']
        hearOthers:
            groups: ['read_registration','write_registration']
        reasonPromotions:
            groups: ['read_registration','write_registration']
        reasonTheBrand:
            groups: ['read_registration','write_registration']
        reasonTechnology:
            groups: ['read_registration','write_registration']
        reasonJapanese:
            groups: ['read_registration','write_registration']
        reasonTheDesign:
            groups: ['read_registration','write_registration']
        reasonAffordable:
            groups: ['read_registration','write_registration']
        reasonDesignerSuggested:
            groups: ['read_registration','write_registration']
        reasonFriendFamilySuggested:
            groups: ['read_registration','write_registration']
        reasonOthers:
            groups: ['read_registration','write_registration']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\ServiceSheet:
    attributes:
        id:
            groups: ['read_service_sheet', 'write_service_sheet', 'read_service_sheet_scalar']
        appointment:
            groups: ['read_service_sheet', 'write_service_sheet', 'read_case_service_sheet']
        case:
            groups: ['read_service_sheet', 'write_service_sheet']
        images:
            groups: ['read_service_sheet', 'read_case_service_sheet']

Magenta\Bundle\SWarrantyModelBundle\Entity\Customer\ServiceNote:
    attributes:
        id:
            groups: ['read_service_note', 'write_service_note', 'read_case_note']
        appointment:
            groups: ['read_service_note', 'write_service_note', 'read_case_note']
        case:
            groups: ['read_service_note', 'write_service_note']
        description:
            groups: ['read_service_note', 'write_service_note', 'read_case_note']

Magenta\Bundle\SWarrantyModelBundle\Entity\Product\Brand:
    attributes:
        id:
            groups: ['read_brand','write_brand']
        name:
            groups: ['read_brand','write_brand']

Magenta\Bundle\SWarrantyModelBundle\Entity\Product\BrandCategory:
    attributes:
        id:
            groups: ['read_category','write_category']
        name:
            groups: ['read_category','write_category']


Magenta\Bundle\SWarrantyModelBundle\Entity\Media\Media:
    attributes:
        id:
            groups: ['read_medium']
        name:
            groups: ['read_medium']
#{
#  "customer": {
#    "name": "new customer"
#  },
#  "product": "/api/products/1",
#  "purchaseDate": "2018-06-14",
#  "productSerialNumber": "S001"
#}

